variables:
  PROJ_NAME: "video_server"
  PUBLIC_REGISTRY: "registry.cn-hangzhou.aliyuncs.com/busy_service/$PROJ_NAME:$CI_COMMIT_SHORT_SHA"
  PRIVATE_REGISTRY: "registry-vpc.cn-hangzhou.aliyuncs.com/busy_service/$PROJ_NAME:$CI_COMMIT_SHORT_SHA"

stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - docker login --username $REGISTRY_USER --password $REGISTRY_PWD registry.cn-hangzhou.aliyuncs.com
    - docker build -t $PROJ_NAME:latest .
    - docker tag $PROJ_NAME:latest $PUBLIC_REGISTRY
    - docker push $PUBLIC_REGISTRY
    - docker rmi $PUBLIC_REGISTRY $PROJ_NAME:latest
  #  when: manual
  tags:
    - idc-workshop


# 部署到测试服
job_deploy_test:
  stage: deploy
  #  when: manual
  script:
    - cd /home/work/www/camera_server
    - docker login --username $REGISTRY_USER --password $REGISTRY_PWD registry.cn-hangzhou.aliyuncs.com
    # 修改 版本名称
    # -i:源文件修改
    # s:替换
    # 此命令含义为 替换 busy_service/video_server:xxxx 为新版本号
    - sed -i "s!busy_service\/video_server:[0-9a-z]*!busy_service\/video_server:$CI_COMMIT_SHORT_SHA!" docker-compose.yml
    - docker-compose up -d video_server
  tags:
    - 208-runner
