version: '3.8'

services:

  video_server:
    image: registry.cn-hangzhou.aliyuncs.com/busy_service/video_server:069dae46
    restart: always
    environment:
      LOC_CFG: /data/config/config.yml
    volumes:
      - ./config/video_server.yml:/data/config/config.yml
    ports:
      - "7012:7012"

  emqx:
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
