version: '3.8'

services:

  vs:
    container_name: vs
    image: registry.cn-hangzhou.aliyuncs.com/busy_service/video_server:8f3f15b0
    restart: always
    environment:
      LOC_CFG: /data/config/config.yml
    volumes:
      - ./config/video_server.yml:/data/config/config.yml
    ports:
      - "7069:7069"
      - "9090:9090/udp"

  emqx:
    container_name: emqx
    image: emqx/emqx:latest
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"